server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
#  thymeleaf:
#    cache: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/MHP
          jwk-set-uri: http://localhost:8081/auth/realms/MHP/protocol/openid-connect/certs
          jws-algorithm: RS256