version: '3.8'

services:
  oauth-keycloak:
    build:
      context: .
      dockerfile: ./OAuthServer.Dockerfile
    volumes:
    - ./data:/tmp
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=demo123
      - KEYCLOAK_LOGLEVEL=DEBUG
    restart: always
